### PR TITLE
New Compiler

### PR DESCRIPTION
**Pull request by evincarofautumn**
The new compiler, based on the reference typechecker. PRing so GitHub shows it as existing.

### CODE REVIEW

**Comment by sullyj3** [comment]
How's the new compiler going? What's left to do?

**Comment by evincarofautumn** [comment]
I haven’t touched it in a little while. Code generation is the biggest thing left to finish—I got hung up on performance details when I should have just done something naïve to improve later. The dictionary code is a bit of a mess (very ad-hoc and dynamic), and I think it needs to be cleaned up in order to move forward.

I have syntax support (here or on my machine) for a few things that don’t have finished semantics, including word/type/vocab synonyms (aliases), trait constraints, and compile-time evaluation (macros). Those aren’t critical for ditching the old compiler, but I think they’ll be necessary before a pre-release announcement.

**Comment by evincarofautumn** [comment]
Moving this over to master. It’ll make it simpler to move away from the old compiler, and there’s not much use in keeping them separated at this point.

**Comment by sullyj3** [comment]
Cool, how do we go about building the new one? It doesn't seem to be referenced in the makefile.

**Comment by evincarofautumn** [comment]
You can run `stack build` in the `new` directory, then `stack exec kitten` to run it. Of course, the interpreter is currently broken. ¯\\\_(ツ)\_/¯

I’m also going to get rid of the Makefile at some point.

**Pull request merged**
